// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalMe.API.Data;

#nullable disable

namespace PortalMe.API.Migrations
{
    [DbContext(typeof(PortalMeDbContext))]
    [Migration("20240307154816_GantiSalt")]
    partial class GantiSalt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PortalMe.API.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<bool>("IsLoggedIn")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_logged_in");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.ToTable("tbl_m_accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("272e2d9a-81b0-4405-88bc-8e4106853242"),
                            Email = "diansastro@mii.co.id",
                            IsLoggedIn = false,
                            Password = "$2a$12$mTQ5p0pYwlVizGgqvcC2O.5Sp97riuTVCWa3tEFxSayvdQg9w1GhG"
                        });
                });

            modelBuilder.Entity("PortalMe.API.Models.AccountRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("RoleId");

                    b.ToTable("tbl_tr_account_roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90c04ed8-27e0-4b23-9d29-f753a76c570a"),
                            AccountId = new Guid("272e2d9a-81b0-4405-88bc-8e4106853242"),
                            RoleId = new Guid("0af9fe84-d6ca-45c1-b7ef-e67507c84a77")
                        },
                        new
                        {
                            Id = new Guid("421c7b68-9864-46b4-b4c9-60f7046cbf84"),
                            AccountId = new Guid("272e2d9a-81b0-4405-88bc-8e4106853242"),
                            RoleId = new Guid("a4bfa4f4-c763-4424-b1f7-0554a1fce433")
                        });
                });

            modelBuilder.Entity("PortalMe.API.Models.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("NameApp")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name_app");

                    b.Property<string>("UrlApp")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("url_app");

                    b.HasKey("Id");

                    b.ToTable("tbl_m_applications");
                });

            modelBuilder.Entity("PortalMe.API.Models.ApplicationPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("application_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("tbl_tr_application_permissions");
                });

            modelBuilder.Entity("PortalMe.API.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("company_name");

                    b.HasKey("Id");

                    b.ToTable("tbl_m_companys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a46d3ae0-49fa-4549-8159-88e4535d4343"),
                            CompanyName = "Metrodata"
                        });
                });

            modelBuilder.Entity("PortalMe.API.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("company_id");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("department");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("photo");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Position");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("tbl_m_employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("272e2d9a-81b0-4405-88bc-8e4106853242"),
                            CompanyId = new Guid("a46d3ae0-49fa-4549-8159-88e4535d4343"),
                            Department = "ADD 1",
                            FirstName = "Dian",
                            LastName = "Sastro",
                            Photo = "profile.jpg",
                            Position = "Appdev"
                        });
                });

            modelBuilder.Entity("PortalMe.API.Models.LogAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)")
                        .HasColumnName("account_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("tbl_m_log_admins");
                });

            modelBuilder.Entity("PortalMe.API.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role_name");

                    b.HasKey("Id");

                    b.ToTable("tbl_m_roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0af9fe84-d6ca-45c1-b7ef-e67507c84a77"),
                            RoleName = "Employee"
                        },
                        new
                        {
                            Id = new Guid("a4bfa4f4-c763-4424-b1f7-0554a1fce433"),
                            RoleName = "Admin"
                        });
                });

            modelBuilder.Entity("PortalMe.API.Models.Account", b =>
                {
                    b.HasOne("PortalMe.API.Models.Employee", "Employee")
                        .WithOne("Account")
                        .HasForeignKey("PortalMe.API.Models.Account", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PortalMe.API.Models.AccountRole", b =>
                {
                    b.HasOne("PortalMe.API.Models.Account", "Account")
                        .WithMany("AccountRoles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalMe.API.Models.Role", "Role")
                        .WithMany("AccountRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PortalMe.API.Models.ApplicationPermission", b =>
                {
                    b.HasOne("PortalMe.API.Models.Account", "Account")
                        .WithMany("ApplicationPermissions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalMe.API.Models.Application", "Application")
                        .WithMany("ApplicationPermissions")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("PortalMe.API.Models.Employee", b =>
                {
                    b.HasOne("PortalMe.API.Models.Company", "Company")
                        .WithMany("Employee")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PortalMe.API.Models.LogAdmin", b =>
                {
                    b.HasOne("PortalMe.API.Models.Account", "Account")
                        .WithMany("LogAdmins")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PortalMe.API.Models.Account", b =>
                {
                    b.Navigation("AccountRoles");

                    b.Navigation("ApplicationPermissions");

                    b.Navigation("LogAdmins");
                });

            modelBuilder.Entity("PortalMe.API.Models.Application", b =>
                {
                    b.Navigation("ApplicationPermissions");
                });

            modelBuilder.Entity("PortalMe.API.Models.Company", b =>
                {
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PortalMe.API.Models.Employee", b =>
                {
                    b.Navigation("Account");
                });

            modelBuilder.Entity("PortalMe.API.Models.Role", b =>
                {
                    b.Navigation("AccountRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
